/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./../components/Banner/index.vue')['default']
    BottomRightLayout: typeof import('./../components/BottomRightLayout/index.vue')['default']
    BottomRightMore: typeof import('./../components/BottomRightMore/index.vue')['default']
    Card: typeof import('./../components/Card/index.vue')['default']
    CardEssay: typeof import('./../components/CardEssay/index.vue')['default']
    CardInfo: typeof import('./../components/CardInfo/index.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElectronicClocks: typeof import('./../components/ElectronicClocks/index.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./../components/Layout/Footer/index.vue')['default']
    Fullscreen: typeof import('./../components/Fullscreen/index.vue')['default']
    Header: typeof import('./../components/Layout/Header/index.vue')['default']
    Layout: typeof import('./../components/Layout/index.vue')['default']
    Loading: typeof import('./../components/Loading/index.vue')['default']
    Main: typeof import('./../components/Layout/Main/index.vue')['default']
    MainToTop: typeof import('./../components/ToTop/MainToTop.vue')['default']
    Menu: typeof import('./../components/Layout/Header/Menu/index.vue')['default']
    MoveMenu: typeof import('./../components/Layout/Header/MoveMenu/index.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RandomArticle: typeof import('./../components/Card/RandomArticle/index.vue')['default']
    ReadingMode: typeof import('./../components/ReadingMode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../components/Layout/SideBar/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TagListCard: typeof import('./../components/Card/TagListCard/index.vue')['default']
    ToTop: typeof import('./../components/ToTop/index.vue')['default']
    Wave: typeof import('./../components/Wave/index.vue')['default']
  }
}
